### ISSUE TITLE
Imageview flipped and ROIs in wrong place

### ISSUE THREAD

**Issue by ercius** [Xi-CAM/Xi-cam.NCEM#14]
The images in the main display are flipped compared to the preview for some images. The preview has the correct orientation compared to other imaging program (like Fiji) and to the original microscope acquisition software:
![image](https://user-images.githubusercontent.com/15657108/96285907-70625100-0f94-11eb-9262-396c55154c50.png)

However, some images are correctly oriented and it does not seem to correspond to file type. Some TIFs are incorrect and some are correct. I modified this image to be obvious of the orientation. It was written out by imageio.imsave() as a tif.
![image](https://user-images.githubusercontent.com/15657108/96286357-1ada7400-0f95-11eb-912b-85d0a5eae990.png)

The last weird thing is that an ROI added to the image is in the wrong place. The ROI in the lower left is showing the blank area in the upper left. So, the data is probably flipped in memory somehow because I use numpy slicing to generate the FFT of the ROI area on the left (shown as blank here). The code to retrieve the data is:
`data = self.Rimageview.imageItem.image`
This used to work as expected, but it might be some change made either with the Catalog viewer or pyqtgraph 0.11.0.
![image](https://user-images.githubusercontent.com/15657108/96286825-d69ba380-0f95-11eb-9310-f6e79ef83b47.png)

**Comment by ercius** [comment]
@ronpandolfi Some clues as to why the preview and the Catalog view are flipped. I do not understand why some TIFs are correct and others are not.

**Comment by ronpandolfi** [comment]
The source of confusion seems to have been PyDM. This package is not a core Xi-CAM dependency, however it is a critical component of the Xi-CAM.Acquire plugin, and installed in our dev environments. PyDM had been setting a global configuration for PyQtGraph at import-time, modifying the default behavior of ImageView. Turns out we've been developing against that for a while now without knowing.

I've put in a PR to PyDM. Their choice for that setting actually makes a lot of sense, even if it should be scoped differently. I suggest applying it in your ImageView subclasses as well. Include this in your blend class's init: `self.imageItem.setOpts(axisOrder="row-major")`

With that change, we should then be in sync. I'm not certain this is the _only_ problem (this doesn't explain the unpredictable behavior for different files), however its definitely a first step to solving this issue. If that doesn't address your ROI issue, I'll look at that next.

https://github.com/slaclab/pydm/pull/705

**Comment by ercius** [comment]
Ok. I set this properly and it fixed the issue of the rotation. It looks like it fixed it for all images I have to test.

The ROI in the FFTviewer was also in the wrong place.  I flip the image before cropping and now the ROI is taken in the correct place and the FFT orientation matches the image orientation.
